"""


1. Around 40-45 min round
2. SQL QUERY OPTIMIZATION IN YOUT PROJECY
3. REST END POINT
4. LRU CACHE DESING
5. MICROSERVICES
6. HOW HANDLE USERS
7. WHERE YOU WANNA SEE IN 5 YEARS MANAGEMENT & ARCHIET SIDE
#forgot more question most of deep technical round
"""